### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by carpedm20** [aikorea/PaperTrend#3]
- [x] pdf 링크
- [x] 분야별 (학회는 자동) 필터
- [x] json request는 한번으로 제한
- [x] 검색어 히스토리 저장

**Comment by kjw0612** [comment]
분야별 필터를 만들어서 분야를 고르면 학회들은 알아서 골라지도록 하는건 어떨까? 
물론 학회별 필터도 있어야겠고.
